name: context demo
on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Please enter the word'
        default: 'Hello'
        required: true
        type: string
      env:
        firstName: 'Anand'
        website: 'Testing Mini Bytes'
jobs:
  contexts-demo:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
        - run: echo  ${{inputs.text}}
        - run: echo ${{github.events.input.text}}
        - run: echo ${{github.actor}}
        - run: echo ' Hi ${{env.firstName}}'
        - run: echo 'website - ${{env.website}}
        - run: echo ${{job.status}}
        - run: echo ${{runner.os}}









